/**
 * Descriptions des groupes et sections CNU issues de Wikipédia.
 * Source : https://fr.wikipedia.org/wiki/Conseil_national_des_universit%C3%A9s
 * Les clés correspondent aux codes numériques (string) stockés en base.
 */

export const CNU_GROUPS: Record<string, string> = {
  "0": "Personnels non rattachés à une section disciplinaire du CNU (personnels des grands établissements, situation sans discipline affectée).",
  "1": "Droit, économie, gestion (1re partie). Regroupe les sections 01 à 04 : Droit privé et sciences criminelles, Droit public, Histoire du droit et des institutions, Science politique.",
  "2": "Droit, économie, gestion (2e partie). Regroupe les sections 05 à 06 : Sciences économiques, Sciences de gestion.",
  "3": "Lettres et sciences humaines — linguistique et langues (1re partie). Regroupe les sections 07 à 15 : Sciences du langage, Langues et littératures anciennes, françaises, comparées, anglaises, germaniques, slaves, romanes, et autres domaines linguistiques.",
  "4": "Lettres et sciences humaines — sciences humaines (1re partie). Regroupe les sections 16 à 24 : Psychologie et Ergonomie, Philosophie, Architecture et Arts, Sociologie et Démographie, Anthropologie et Préhistoire, Histoire, Géographie, Urbanisme.",
  "5": "Mathématiques et informatique. Regroupe les sections 25 à 27 : Mathématiques, Mathématiques appliquées, Informatique.",
  "6": "Physique. Regroupe les sections 28 à 30 : Milieux denses et matériaux, Constituants élémentaires, Milieux dilués et optique.",
  "7": "Chimie. Regroupe les sections 31 à 33 : Chimie théorique, physique et analytique ; Chimie organique, inorganique et industrielle ; Chimie des matériaux.",
  "8": "Sciences de la Terre, de l'Univers et de l'Environnement. Regroupe les sections 34 à 37 : Astronomie et astrophysique, Structure et évolution de la Terre, Géodynamique des enveloppes supérieures, Météorologie et océanographie physique.",
  "9": "Sciences de l'ingénieur et instrumentation. Regroupe les sections 60 à 63 : Mécanique et génie mécanique, Génie informatique et automatique, Énergétique et génie des procédés, Génie électrique et électronique.",
  "10": "Biologie et sciences du vivant. Regroupe les sections 64 à 69 : Biochimie et biologie moléculaire, Biologie cellulaire, Physiologie, Biologie des populations et écologie, Biologie des organismes, Neurosciences.",
  "11": "Lettres et sciences humaines (2e partie). Regroupe les sections 70 à 74 : Sciences de l'éducation, Sciences de l'information et de la communication, Épistémologie et histoire des sciences, Cultures et langues régionales, STAPS.",
};

export const CNU_SECTIONS: Record<string, string> = {
  "0": "Section sans discipline : personnels non rattachés à une section CNU disciplinaire.",
  "1": "Droit privé et sciences criminelles.",
  "2": "Droit public.",
  "3": "Histoire du droit et des institutions.",
  "4": "Science politique.",
  "5": "Sciences économiques.",
  "6": "Sciences de gestion.",
  "7": "Sciences du langage : linguistique et phonétique générales.",
  "8": "Langues et littératures anciennes.",
  "9": "Langue et littérature françaises.",
  "10": "Littératures comparées.",
  "11": "Langues et littératures anglaises et anglo-saxonnes.",
  "12": "Langues et littératures germaniques et scandinaves.",
  "13": "Langues et littératures slaves.",
  "14": "Langues et littératures romanes : espagnol, italien, portugais, autres langues romanes.",
  "15": "Langues et littératures arabes, chinoises, japonaises, hébraïques, d'autres domaines linguistiques.",
  "16": "Psychologie et Ergonomie.",
  "17": "Philosophie.",
  "18": "Architecture et Arts : plastiques, du spectacle, musique, musicologie, esthétique, sciences de l'art.",
  "19": "Sociologie, démographie.",
  "20": "Anthropologie biologique, ethnologie, préhistoire.",
  "21": "Histoire et civilisations : histoire et archéologie des mondes anciens et des mondes médiévaux ; de l'art.",
  "22": "Histoire et civilisations : histoire des mondes modernes, histoire du monde contemporain ; de l'art ; de la musique.",
  "23": "Géographie physique, humaine, économique et régionale.",
  "24": "Aménagement de l'espace, urbanisme.",
  "25": "Mathématiques.",
  "26": "Mathématiques appliquées et applications des mathématiques.",
  "27": "Informatique.",
  "28": "Milieux denses et matériaux.",
  "29": "Constituants élémentaires.",
  "30": "Milieux dilués et optique.",
  "31": "Chimie théorique, physique, analytique.",
  "32": "Chimie organique, inorganique, industrielle.",
  "33": "Chimie des matériaux.",
  "34": "Astronomie, astrophysique.",
  "35": "Structure et évolution de la Terre et des autres planètes.",
  "36": "Terre solide : géodynamique des enveloppes supérieures, paléobiosphère.",
  "37": "Météorologie, océanographie physique et physique de l'environnement.",
  "42": "Morphologie et morphogenèse (médecine).",
  "43": "Biophysique et imagerie médicale.",
  "44": "Biochimie, biologie cellulaire et moléculaire, physiologie et nutrition.",
  "45": "Microbiologie, maladies transmissibles et hygiène.",
  "46": "Santé publique, environnement et société.",
  "47": "Cancérologie, génétique, hématologie, immunologie.",
  "48": "Anesthésiologie, réanimation, médecine d'urgence, pharmacologie et thérapeutique.",
  "49": "Pathologie nerveuse et musculaire, pathologie mentale, handicap et rééducation.",
  "50": "Pathologie ostéo-articulaire, dermatologie et chirurgie plastique.",
  "51": "Pathologie cardiorespiratoire et vasculaire.",
  "52": "Maladies des appareils digestif et urinaire.",
  "53": "Médecine interne, gériatrie, chirurgie générale et médecine générale.",
  "54": "Développement et pathologie de l'enfant, gynécologie-obstétrique, endocrinologie et reproduction.",
  "55": "Pathologie de la tête et du cou.",
  "56": "Développement, croissance et prévention (odontologie).",
  "57": "Sciences biologiques, médecine et chirurgie buccales.",
  "58": "Sciences physiques et physiologiques endodontiques et prothétiques.",
  "60": "Mécanique, génie mécanique, génie civil.",
  "61": "Génie informatique, automatique et traitement du signal.",
  "62": "Énergétique, génie des procédés.",
  "63": "Génie électrique, électronique, optronique et systèmes.",
  "64": "Biochimie et biologie moléculaire.",
  "65": "Biologie cellulaire.",
  "66": "Physiologie.",
  "67": "Biologie des populations et écologie.",
  "68": "Biologie des organismes.",
  "69": "Neurosciences.",
  "70": "Sciences de l'éducation.",
  "71": "Sciences de l'information et de la communication.",
  "72": "Épistémologie, histoire des sciences et des techniques.",
  "73": "Cultures et langues régionales.",
  "74": "Sciences et techniques des activités physiques et sportives (STAPS).",
  "76": "Théologie catholique.",
  "77": "Théologie protestante.",
  "80": "Sciences physico-chimiques et ingénierie appliquée à la santé (pharmacie, bi-appartenants).",
  "81": "Sciences du médicament et des autres produits de santé (pharmacie, bi-appartenants).",
  "82": "Sciences biologiques, fondamentales et cliniques (pharmacie, bi-appartenants).",
  "85": "Sciences physico-chimiques et ingénierie appliquée à la santé (pharmacie, mono-appartenants).",
  "86": "Sciences du médicament et des autres produits de santé (pharmacie, mono-appartenants).",
  "87": "Sciences biologiques, fondamentales et cliniques (pharmacie, mono-appartenants).",
  "90": "Maïeutique.",
  "91": "Sciences de la rééducation et de la réadaptation.",
  "92": "Sciences infirmières.",
};
